# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Xilinx/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/Wave_Ram/Wave_Ram.xci
# IP: The module: 'Wave_Ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/Wave_Ram/Wave_Ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wave_Ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Xilinx/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/Wave_Ram/Wave_Ram.xci
# IP: The module: 'Wave_Ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/ADC-Interface/ADC_Demo/ADC_Demo.srcs/sources_1/ip/Wave_Ram/Wave_Ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Wave_Ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
